### PR TITLE
[180] Add writable memory permissions and checks

### LINKED ISSUE #180: Track whether memory is writable
Example test case that should fail
```c
#include "caffeine.h"

const char data[] = "abcdef";

__attribute__((noinline)) void write_to_data(char* mem) {
  *mem = 'u';
}

void test() {
  write_to_data((char*)data);
}
```

General instructions:
- Add a field to `Allocation` to indicating whether it's writable
- Modify `MemHeap::alloc` to to take a parameter that initializes whether the allocation is writable
- Fix up all call sites to now pass in the correct writability (there should be a LLVM attribute which indicates whether a newly created allocation is writable)
- Finally, make sure that writes to an allocation first check whether that allocation is writable and emit an error otherwise

### PR DESCRIPTION
**Pull request by Skrinikov**
As per comments from last PR I changed the boolean flag to an general enum type

Fixes #180

### CODE REVIEW

File: include/caffeine/Memory/MemHeap.h [hunk 1]
```diff
@@ -27,6 +27,16 @@ class Solver;
...
 
+/**
+ * Permisisons for an allocation
+ *
+ * This is used to indicate what kind of operations a user is allowed
+ * to perfom on the requested allocation. As an example, for an allocation
+ * with ReadWrite permissions a user could can read and modify the underlying
+ * memory. For a Read, a user can read the data, but cannot modify the buffer.
+ */
+enum class AllocationPermissions { None, Read, Write, ReadWrite };
```
Comment (Phantomical) [inline include/caffeine/Memory/MemHeap.h:38]: If we make this a bitfield then you can easily do `is_readable` or `is_writable checks.

```suggestion
enum class AllocationPermissions { 
  None = 0,
  Read = 1,
  Write = 2, 
  ReadWrite = 3
};
```

I do realize this doesn't change the semantics at all but it makes the values explicit so that they can be relied upon :)

File: src/Memory/MemHeap.cpp [hunk 2]
```diff
@@ -16,20 +16,29 @@ namespace caffeine {
...
 Allocation::Allocation(const OpRef& address, const ConstantInt& size,
-                       const OpRef& data, AllocationKind kind)
-    : Allocation(address, make_ref<Operation>(size), data, kind) {}
+                       const OpRef& data, AllocationKind kind,
+                       AllocationPermissions permissions)
+    : Allocation(address, make_ref<Operation>(size), data, kind, permissions) {}
 
 void Allocation::overwrite(const OpRef& newdata) {
+  CAFFEINE_ASSERT(perms_ == AllocationPermissions::Write ||
+                      perms_ == AllocationPermissions::ReadWrite,
```
Comment (Phantomical) [inline src/Memory/MemHeap.cpp:34]: Using the bitfield idea:
```suggestion
  CAFFEINE_ASSERT(perms_ & AllocationPermissions::Write,
```

File: src/Memory/MemHeap.cpp [hunk 3]
```diff
@@ -16,20 +16,29 @@ namespace caffeine {
...
+                  "tried to write to unwritable allocation");
   data_ = newdata;
 }
 void Allocation::overwrite(OpRef&& newdata) {
+  CAFFEINE_ASSERT(perms_ == AllocationPermissions::Write ||
+                      perms_ == AllocationPermissions::ReadWrite,
```
Comment (Phantomical) [inline src/Memory/MemHeap.cpp:40]: Same here:
```suggestion
  CAFFEINE_ASSERT(perms_ & AllocationPermissions::Write,
```

File: src/Memory/MemHeap.cpp [hunk 4]
```diff
@@ -166,6 +175,9 @@ void Allocation::write(const OpRef& offset, const OpRef& value_,
 
   CAFFEINE_ASSERT(offset->type().is_int(),
                   "tried to write at non-integer offset");
+  CAFFEINE_ASSERT(perms_ == AllocationPermissions::Write ||
+                      perms_ == AllocationPermissions::ReadWrite,
```
Comment (Phantomical) [inline src/Memory/MemHeap.cpp:179]:
```suggestion
  CAFFEINE_ASSERT(perms_ & AllocationPermissions::Write,
```

File: src/Memory/MemHeap.cpp [hunk 5]
```diff
@@ -204,6 +216,9 @@ void Allocation::write(const OpRef& offset, const LLVMScalar& value,
 void Allocation::write(const OpRef& offset, llvm::Type* type,
                        const LLVMValue& value, const MemHeap& heap,
                        const llvm::DataLayout& layout) {
+  CAFFEINE_ASSERT(perms_ == AllocationPermissions::Write ||
+                      perms_ == AllocationPermissions::ReadWrite,
```
Comment (Phantomical) [inline src/Memory/MemHeap.cpp:220]:
```suggestion
  CAFFEINE_ASSERT(perms_ & AllocationPermissions::Write,
```

File: src/Interpreter/ExprEval.cpp [hunk 6]
```diff
@@ -356,7 +356,7 @@ OpRef ExprEvaluator::visitGlobalData(llvm::Constant& constant, unsigned AS) {
       bitwidth, layout.getTypeAllocSizeInBits(type).getFixedSize()));
   Allocation alloc{ConstantInt::CreateZero(bitwidth), size,
                    AllocOp::Create(size, ConstantInt::CreateZero(8)),
-                   AllocationKind::Alloca};
+                   AllocationKind::Alloca, AllocationPermissions::ReadWrite};
   alloc.write(ConstantInt::CreateZero(bitwidth), type, value, ctx->heap,
               layout);
```
Comment (Phantomical) [inline src/Interpreter/ExprEval.cpp:361]: At the end of this you probably want to update the permissions to be either `Read` or `ReadWrite` depending on what attributes the global has. I'm not sure which attributes are relevant here. You'll have to figure that out from the llvm reference page.

**Review by Phantomical — COMMENTED** [review]
This approach looks good to me! Currently everything is set as `ReadWrite` so I think you might want to try and get it so that the test case in the linked issue passes.

If you want to do that in a second PR then that also works (but then this one shouldn't be closing that issue). If this is the case then LMK and I'll approve once the other comments are addressed :)

**Review by Phantomical — APPROVED** [review]
LGTM!
